version: '3'

services:
  flatdocker:
    build:
      context: .
    volumes:
      - .:/flatdocker
    ports:
        - "8000:8000"
    command: >
      sh -c "python flatbond/manage.py runserver 0.0.0.0:8000"
    depends_on:
    - db
  db:
    image: postgres
