# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flatbond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_memebership_fee', models.BooleanField(default=False)),
                ('rent', models.IntegerField()),
            ],
        ),
    ]
