# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flatbond_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatbond',
            name='postcode',
            field=models.CharField(default='cm23 3rg', max_length=20),
            preserve_default=False,
        ),
    ]
