# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190207_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatbond',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
